import { EvidenceAsset, EvidenceParseStatus, ObservationDomain, Prisma } from "@prisma/client";

type MockParseTargetStatus = Extract<EvidenceParseStatus, "parsed" | "needs_review">;

type SuggestedObservation = {
  observation_domain: ObservationDomain;
  metric_key: string;
  value_numeric: number;
  unit: string;
};

function buildSuggestedObservation(asset: EvidenceAsset): SuggestedObservation {
  if (asset.domain_hint === "body_metric") {
    return {
      observation_domain: "body",
      metric_key: "bodyweight",
      value_numeric: 70.0,
      unit: "kg",
    };
  }

  if (asset.domain_hint === "health" || asset.domain_hint === "rehab") {
    return {
      observation_domain: "recovery",
      metric_key: "fatigue_score",
      value_numeric: 4,
      unit: "score",
    };
  }

  return {
    observation_domain: "recovery",
    metric_key: "sleep_hours",
    value_numeric: 7,
    unit: "hour",
  };
}

export function buildMockParsedSummary(
  asset: EvidenceAsset,
  targetStatus: MockParseTargetStatus,
): Prisma.InputJsonValue {
  return {
    mock_parser: {
      enabled: true,
      version: "mock-evidence-parser-v1",
      decided_status: targetStatus,
      generated_at: new Date().toISOString(),
    },
    suggested_observation: buildSuggestedObservation(asset),
    note: "This parsed_summary is generated by MOCK parse logic, not real AI vision.",
  } as Prisma.InputJsonObject;
}
